### ISSUE TITLE
struct_pack pack string error

### ISSUE THREAD

**Issue by souce** [amozzhuhin/struct#1]
Hi man, your project "struct" is really great, I've never seen anything so great.
I have a problem today, when I pack string "key_001", but I got "key_",
in "struct.c" fucntion "struct_pack_str", I found something:

for (i = 0; i < context->repeat; i++)
{
	if (str != NULL && *str != '0') //line 623, String end flag is '\0'
		*p++ = *str++;
	else
		*p++ = 0;
}

have a nice day.

**Comment by amozzhuhin** [comment]
Hi!

Thank you for reporting this issue! Now must be fixed.

Sorry for the late answer, somehow lost the notification  :-)
